In [97]:
# IMPORTS!

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', 200)

In [98]:
# ROUND 1 of cleaning...

la_cleaning1 = pd.read_csv('./LA_data/air_walk_merged_LA.csv')

In [99]:
la_cleaning1.shape

(612, 140)

In [100]:
la_cleaning1.head(3)

,id,lat,lon,name,location_type,pm_2.5,temp_f,temp_c,humidity,pressure,last_seen,model,hidden,flagged,downgraded,age,is_owner,10min_avg,30min_avg,1hour_avg,6hour_avg,1day_avg,1week_avg,fips_id,OBJECTID,GEOID20,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,CSA,CSA_Name,CBSA,CBSA_Name,CBSA_POP,CBSA_EMP,CBSA_WRK,Ac_Total,Ac_Water,Ac_Land,Ac_Unpr,TotPop,CountHU,HH,P_WrkAge,AutoOwn0,Pct_AO0,AutoOwn1,Pct_AO1,AutoOwn2p,Pct_AO2p,Workers,R_LowWageWk,R_MedWageWk,R_HiWageWk,R_PCTLOWWAGE,TotEmp,E5_Ret,E5_Off,E5_Ind,E5_Svc,E5_Ent,E8_Ret,E8_off,E8_Ind,E8_Svc,E8_Ent,E8_Ed,E8_Hlth,E8_Pub,E_LowWageWk,E_MedWageWk,E_HiWageWk,E_PctLowWage,D1A,D1B,D1C,D1C5_RET,D1C5_OFF,D1C5_IND,D1C5_SVC,D1C5_ENT,D1C8_RET,D1C8_OFF,D1C8_IND,D1C8_SVC,D1C8_ENT,D1C8_ED,D1C8_HLTH,D1C8_PUB,D1D,D1_FLAG,D2A_JPHH,D2B_E5MIX,D2B_E5MIXA,D2B_E8MIX,D2B_E8MIXA,D2A_EPHHM,D2C_TRPMX1,D2C_TRPMX2,D2C_TRIPEQ,D2R_JOBPOP,D2R_WRKEMP,D2A_WRKEMP,D2C_WREMLX,D3A,D3AAO,D3AMM,D3APO,D3B,D3BAO,D3BMM3,D3BMM4,D3BPO3,D3BPO4,D4A,D4B025,D4B050,D4C,D4D,D4E,D5AR,D5AE,D5BR,D5BE,D5CR,D5CRI,D5CE,D5CEI,D5DR,D5DRI,D5DE,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area
0,47959,33.767104,-118.198957,100 Oceangate,inside,0.82,86.0,30.000000,17.0,1012.79,2022-02-12 21:40:46,PMS5003+PMS5003+BME280,False,False,False,0,False,0.86,0.81,1.21,2.22,1.62,2.35,60375760012,36060,6.037576e+10,6,37,576001,2,348.0,"Los Angeles-Long Beach, CA",31080.0,"Los Angeles-Long Beach-Anaheim, CA",13262234,6249699,5825012,445.189692,166.96547,278.224222,257.310620,2779,1960.0,1667.0,0.787,133,0.079784,921,0.552490,613,0.367726,1135,177,359,599,0.155947,36518,127,10751,16461,5522,3657,127,6243,16461,4247,3657,8,1267,4508,4063,6585,25870,0.111260,7.617253,10.800176,141.921853,0.493567,41.782185,63.973263,21.460443,14.212394,0.493567,24.262504,63.973263,16.505343,14.212394,0.031091,4.924010,17.519681,149.539106,0,21.906419,0.779748,0.779748,0.739722,0.739722,0.769949,0.727922,0.693137,0.385297,0.141436,0.060287,0.031081,0.379493,47.203383,9.815321,7.468784,29.919279,350.517864,46.006059,23.00303,36.804847,292.138476,103.513633,91.2,0.332764,0.713611,25.33,58.266674,0.009115,262455,258680,124964,150137,0.000106,0.383448,0.000119,0.503080,0.000068,0.104685,0.000111,0.149839,18,17,20,20,19.166667,6972.639103,1.801666e+06
1,94345,34.138132,-118.009183,1230 S Mayflower (Inside),inside,0.00,94.0,34.444444,11.0,1002.99,2022-02-12 21:40:24,PMS5003+PMS5003+BME280,False,False,False,1,False,0.22,0.30,0.35,1.32,1.10,2.25,60374309011,48853,6.037431e+10,6,37,430901,1,348.0,"Los Angeles-Long Beach, CA",31080.0,"Los Angeles-Long Beach-Anaheim, CA",13262234,6249699,5825012,111.226876,0.00000,111.226876,111.226876,1509,593.0,548.0,0.654,16,0.029197,252,0.459854,280,0.510949,840,198,280,362,0.235714,817,377,22,95,243,80,377,22,95,104,80,85,54,0,234,383,200,0.286414,5.331445,13.566865,7.345347,3.389469,0.197794,0.854110,2.184724,0.719251,3.389469,0.197794,0.854110,0.935026,0.719251,0.764204,0.485494,0.000000,12.676792,0,1.490876,0.803137,0.803137,0.827030,0.773923,0.807735,0.774577,0.841330,0.500957,0.702494,0.986119,1.028152,0.972241,27.355800,1.515533,6.568010,19.272257,182.263862,0.000000,46.03204,23.016020,115.080100,51.786045,0.0,0.020107,0.393098,5.33,30.668847,0.003532,275265,256737,118588,86030,0.000111,0.402163,0.000118,0.499301,0.000064,0.099344,0.000064,0.085859,19,18,19,20,19.166667,3024.620797,4.501286e+05
2,95367,34.138150,-118.009264,1230 S Mayflower (Outside),outside,0.30,103.0,39.444444,3.0,1003.45,2022-02-12 21:41:08,PMS5003+PMS5003+BME280,False,False,False,0,False,0.68,1.11,1.32,3.78,4.22,9.61,60374309011,48853,6.037431e+10,6,37,430901,1,348.0,"Los Angeles-Long Beach, CA",31080.0,"Los Angeles-Long Beach-Anaheim, CA",13262234,6249699,5825012,111.226876,0.00000,111.226876,111.226876,1509,593.0,548.0,0.654,16,0.029197,252,0.459854,280,0.510949,840,198,280,362,0.235714,817,377,22,95,243,80,377,22,95,104,80,85,54,0,234,383,200,0.286414,5.331445,13.566865,7.345347,3.389469,0.197794,0.854110,2.184724,0.719251,3.389469,0.197794,0.854110,0.935026,0.719251,0.764204,0.485494,0.000000,12.676792,0,1.490876,0.803137,0.803137,0.827030,0.773923,0.807735,0.774577,0.841330,0.500957,0.702494,0.986119,1.028152,0.972241,27.355800,1.515533,6.568010,19.272257,182.263862,0.000000,46.03204,23.016020,115.080100,51.786045,0.0,0.020107,0.393098,5.33,30.668847,0.003532,275265,256737,118588,86030,0.000111,0.402163,0.000118,0.499301,0.000064,0.099344,0.000064,0.085859,19,18,19,20,19.166667,3024.620797,4.501286e+05

In [101]:
la_cleaning1['hidden'].value_counts()

False    612
Name: hidden, dtype: int64

In [102]:
la_cleaning1['flagged'].value_counts()

False    612
Name: flagged, dtype: int64

In [103]:
la_cleaning1['downgraded'].value_counts()

False    612
Name: downgraded, dtype: int64

In [104]:
la_cleaning1['is_owner'].value_counts()

False    612
Name: is_owner, dtype: int64

In [105]:
# COLUMNS TO DROP FOR ROUND 2 OF CLEANING
# Dropping these columns because the data is redundant or provides no information

drop_cols1 = [
    'id', 'lat', 'lon', 'name', 'temp_f', 'temp_c', 'humidity', 'pressure',
    'hidden', 'flagged', 'downgraded', 'is_owner', 'pm_2.5', '10min_avg', '30min_avg',
    '1hour_avg', '6hour_avg', '1day_avg', 'OBJECTID', 'GEOID20', 'STATEFP',
    'COUNTYFP'
]

# kept 'last_seen' for now

In [106]:
# ROUND 2 of cleaning...

la_cleaning2= la_cleaning1.drop(columns=drop_cols1)
la_cleaning2.head(3)

,location_type,last_seen,model,age,1week_avg,fips_id,TRACTCE,BLKGRPCE,CSA,CSA_Name,CBSA,CBSA_Name,CBSA_POP,CBSA_EMP,CBSA_WRK,Ac_Total,Ac_Water,Ac_Land,Ac_Unpr,TotPop,CountHU,HH,P_WrkAge,AutoOwn0,Pct_AO0,AutoOwn1,Pct_AO1,AutoOwn2p,Pct_AO2p,Workers,R_LowWageWk,R_MedWageWk,R_HiWageWk,R_PCTLOWWAGE,TotEmp,E5_Ret,E5_Off,E5_Ind,E5_Svc,E5_Ent,E8_Ret,E8_off,E8_Ind,E8_Svc,E8_Ent,E8_Ed,E8_Hlth,E8_Pub,E_LowWageWk,E_MedWageWk,E_HiWageWk,E_PctLowWage,D1A,D1B,D1C,D1C5_RET,D1C5_OFF,D1C5_IND,D1C5_SVC,D1C5_ENT,D1C8_RET,D1C8_OFF,D1C8_IND,D1C8_SVC,D1C8_ENT,D1C8_ED,D1C8_HLTH,D1C8_PUB,D1D,D1_FLAG,D2A_JPHH,D2B_E5MIX,D2B_E5MIXA,D2B_E8MIX,D2B_E8MIXA,D2A_EPHHM,D2C_TRPMX1,D2C_TRPMX2,D2C_TRIPEQ,D2R_JOBPOP,D2R_WRKEMP,D2A_WRKEMP,D2C_WREMLX,D3A,D3AAO,D3AMM,D3APO,D3B,D3BAO,D3BMM3,D3BMM4,D3BPO3,D3BPO4,D4A,D4B025,D4B050,D4C,D4D,D4E,D5AR,D5AE,D5BR,D5BE,D5CR,D5CRI,D5CE,D5CEI,D5DR,D5DRI,D5DE,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area
0,inside,2022-02-12 21:40:46,PMS5003+PMS5003+BME280,0,2.35,60375760012,576001,2,348.0,"Los Angeles-Long Beach, CA",31080.0,"Los Angeles-Long Beach-Anaheim, CA",13262234,6249699,5825012,445.189692,166.96547,278.224222,257.310620,2779,1960.0,1667.0,0.787,133,0.079784,921,0.552490,613,0.367726,1135,177,359,599,0.155947,36518,127,10751,16461,5522,3657,127,6243,16461,4247,3657,8,1267,4508,4063,6585,25870,0.111260,7.617253,10.800176,141.921853,0.493567,41.782185,63.973263,21.460443,14.212394,0.493567,24.262504,63.973263,16.505343,14.212394,0.031091,4.924010,17.519681,149.539106,0,21.906419,0.779748,0.779748,0.739722,0.739722,0.769949,0.727922,0.693137,0.385297,0.141436,0.060287,0.031081,0.379493,47.203383,9.815321,7.468784,29.919279,350.517864,46.006059,23.00303,36.804847,292.138476,103.513633,91.2,0.332764,0.713611,25.33,58.266674,0.009115,262455,258680,124964,150137,0.000106,0.383448,0.000119,0.503080,0.000068,0.104685,0.000111,0.149839,18,17,20,20,19.166667,6972.639103,1.801666e+06
1,inside,2022-02-12 21:40:24,PMS5003+PMS5003+BME280,1,2.25,60374309011,430901,1,348.0,"Los Angeles-Long Beach, CA",31080.0,"Los Angeles-Long Beach-Anaheim, CA",13262234,6249699,5825012,111.226876,0.00000,111.226876,111.226876,1509,593.0,548.0,0.654,16,0.029197,252,0.459854,280,0.510949,840,198,280,362,0.235714,817,377,22,95,243,80,377,22,95,104,80,85,54,0,234,383,200,0.286414,5.331445,13.566865,7.345347,3.389469,0.197794,0.854110,2.184724,0.719251,3.389469,0.197794,0.854110,0.935026,0.719251,0.764204,0.485494,0.000000,12.676792,0,1.490876,0.803137,0.803137,0.827030,0.773923,0.807735,0.774577,0.841330,0.500957,0.702494,0.986119,1.028152,0.972241,27.355800,1.515533,6.568010,19.272257,182.263862,0.000000,46.03204,23.016020,115.080100,51.786045,0.0,0.020107,0.393098,5.33,30.668847,0.003532,275265,256737,118588,86030,0.000111,0.402163,0.000118,0.499301,0.000064,0.099344,0.000064,0.085859,19,18,19,20,19.166667,3024.620797,4.501286e+05
2,outside,2022-02-12 21:41:08,PMS5003+PMS5003+BME280,0,9.61,60374309011,430901,1,348.0,"Los Angeles-Long Beach, CA",31080.0,"Los Angeles-Long Beach-Anaheim, CA",13262234,6249699,5825012,111.226876,0.00000,111.226876,111.226876,1509,593.0,548.0,0.654,16,0.029197,252,0.459854,280,0.510949,840,198,280,362,0.235714,817,377,22,95,243,80,377,22,95,104,80,85,54,0,234,383,200,0.286414,5.331445,13.566865,7.345347,3.389469,0.197794,0.854110,2.184724,0.719251,3.389469,0.197794,0.854110,0.935026,0.719251,0.764204,0.485494,0.000000,12.676792,0,1.490876,0.803137,0.803137,0.827030,0.773923,0.807735,0.774577,0.841330,0.500957,0.702494,0.986119,1.028152,0.972241,27.355800,1.515533,6.568010,19.272257,182.263862,0.000000,46.03204,23.016020,115.080100,51.786045,0.0,0.020107,0.393098,5.33,30.668847,0.003532,275265,256737,118588,86030,0.000111,0.402163,0.000118,0.499301,0.000064,0.099344,0.000064,0.085859,19,18,19,20,19.166667,3024.620797,4.501286e+05

In [107]:
la_cleaning2['CSA'].value_counts()

348.0    612
Name: CSA, dtype: int64

In [108]:
la_cleaning2['CSA_Name'].value_counts()

Los Angeles-Long Beach, CA    612
Name: CSA_Name, dtype: int64

In [109]:
la_cleaning2['CBSA_POP'].value_counts()

13262234    612
Name: CBSA_POP, dtype: int64

In [110]:
# COLUMNS TO DROP FOR ROUND 3 OF CLEANING
# Dropping these columns because the data is redundant or provides no information

drop_cols2 = [
    'CSA', 'CSA_Name', 'CBSA_POP', 'CBSA_EMP', 'CBSA_WRK', 'AutoOwn0',
    'AutoOwn1', 'AutoOwn2p', 'Workers', 'R_LowWageWk', 'R_MedWageWk',
    'R_HiWageWk'
]

In [111]:
la_cleaning3= la_cleaning2.drop(columns=drop_cols2)
la_cleaning3.head(3)

,location_type,last_seen,model,age,1week_avg,fips_id,TRACTCE,BLKGRPCE,CBSA,CBSA_Name,Ac_Total,Ac_Water,Ac_Land,Ac_Unpr,TotPop,CountHU,HH,P_WrkAge,Pct_AO0,Pct_AO1,Pct_AO2p,R_PCTLOWWAGE,TotEmp,E5_Ret,E5_Off,E5_Ind,E5_Svc,E5_Ent,E8_Ret,E8_off,E8_Ind,E8_Svc,E8_Ent,E8_Ed,E8_Hlth,E8_Pub,E_LowWageWk,E_MedWageWk,E_HiWageWk,E_PctLowWage,D1A,D1B,D1C,D1C5_RET,D1C5_OFF,D1C5_IND,D1C5_SVC,D1C5_ENT,D1C8_RET,D1C8_OFF,D1C8_IND,D1C8_SVC,D1C8_ENT,D1C8_ED,D1C8_HLTH,D1C8_PUB,D1D,D1_FLAG,D2A_JPHH,D2B_E5MIX,D2B_E5MIXA,D2B_E8MIX,D2B_E8MIXA,D2A_EPHHM,D2C_TRPMX1,D2C_TRPMX2,D2C_TRIPEQ,D2R_JOBPOP,D2R_WRKEMP,D2A_WRKEMP,D2C_WREMLX,D3A,D3AAO,D3AMM,D3APO,D3B,D3BAO,D3BMM3,D3BMM4,D3BPO3,D3BPO4,D4A,D4B025,D4B050,D4C,D4D,D4E,D5AR,D5AE,D5BR,D5BE,D5CR,D5CRI,D5CE,D5CEI,D5DR,D5DRI,D5DE,D5DEI,D2A_Ranked,D2B_Ranked,D3B_Ranked,D4A_Ranked,NatWalkInd,Shape_Length,Shape_Area
0,inside,2022-02-12 21:40:46,PMS5003+PMS5003+BME280,0,2.35,60375760012,576001,2,31080.0,"Los Angeles-Long Beach-Anaheim, CA",445.189692,166.96547,278.224222,257.310620,2779,1960.0,1667.0,0.787,0.079784,0.552490,0.367726,0.155947,36518,127,10751,16461,5522,3657,127,6243,16461,4247,3657,8,1267,4508,4063,6585,25870,0.111260,7.617253,10.800176,141.921853,0.493567,41.782185,63.973263,21.460443,14.212394,0.493567,24.262504,63.973263,16.505343,14.212394,0.031091,4.924010,17.519681,149.539106,0,21.906419,0.779748,0.779748,0.739722,0.739722,0.769949,0.727922,0.693137,0.385297,0.141436,0.060287,0.031081,0.379493,47.203383,9.815321,7.468784,29.919279,350.517864,46.006059,23.00303,36.804847,292.138476,103.513633,91.2,0.332764,0.713611,25.33,58.266674,0.009115,262455,258680,124964,150137,0.000106,0.383448,0.000119,0.503080,0.000068,0.104685,0.000111,0.149839,18,17,20,20,19.166667,6972.639103,1.801666e+06
1,inside,2022-02-12 21:40:24,PMS5003+PMS5003+BME280,1,2.25,60374309011,430901,1,31080.0,"Los Angeles-Long Beach-Anaheim, CA",111.226876,0.00000,111.226876,111.226876,1509,593.0,548.0,0.654,0.029197,0.459854,0.510949,0.235714,817,377,22,95,243,80,377,22,95,104,80,85,54,0,234,383,200,0.286414,5.331445,13.566865,7.345347,3.389469,0.197794,0.854110,2.184724,0.719251,3.389469,0.197794,0.854110,0.935026,0.719251,0.764204,0.485494,0.000000,12.676792,0,1.490876,0.803137,0.803137,0.827030,0.773923,0.807735,0.774577,0.841330,0.500957,0.702494,0.986119,1.028152,0.972241,27.355800,1.515533,6.568010,19.272257,182.263862,0.000000,46.03204,23.016020,115.080100,51.786045,0.0,0.020107,0.393098,5.33,30.668847,0.003532,275265,256737,118588,86030,0.000111,0.402163,0.000118,0.499301,0.000064,0.099344,0.000064,0.085859,19,18,19,20,19.166667,3024.620797,4.501286e+05
2,outside,2022-02-12 21:41:08,PMS5003+PMS5003+BME280,0,9.61,60374309011,430901,1,31080.0,"Los Angeles-Long Beach-Anaheim, CA",111.226876,0.00000,111.226876,111.226876,1509,593.0,548.0,0.654,0.029197,0.459854,0.510949,0.235714,817,377,22,95,243,80,377,22,95,104,80,85,54,0,234,383,200,0.286414,5.331445,13.566865,7.345347,3.389469,0.197794,0.854110,2.184724,0.719251,3.389469,0.197794,0.854110,0.935026,0.719251,0.764204,0.485494,0.000000,12.676792,0,1.490876,0.803137,0.803137,0.827030,0.773923,0.807735,0.774577,0.841330,0.500957,0.702494,0.986119,1.028152,0.972241,27.355800,1.515533,6.568010,19.272257,182.263862,0.000000,46.03204,23.016020,115.080100,51.786045,0.0,0.020107,0.393098,5.33,30.668847,0.003532,275265,256737,118588,86030,0.000111,0.402163,0.000118,0.499301,0.000064,0.099344,0.000064,0.085859,19,18,19,20,19.166667,3024.620797,4.501286e+05

In [112]:
la_cleaning3.shape

(612, 106)

In [113]:
# DROPPED A BUNCH OF WALKABILITY COLUMNS FOR ROUND 4 OF CLEANING
# Dropping these columns because these features are integrated into
# the walkability index. We may pull some of these features back in
# later.

la_cleaning4 = la_cleaning3.iloc[:, 0:23]
la_cleaning4['NatWalkInd'] = la_cleaning3['NatWalkInd']     # Adding back the walkability index
la_cleaning4.head(3)

,location_type,last_seen,model,age,1week_avg,fips_id,TRACTCE,BLKGRPCE,CBSA,CBSA_Name,Ac_Total,Ac_Water,Ac_Land,Ac_Unpr,TotPop,CountHU,HH,P_WrkAge,Pct_AO0,Pct_AO1,Pct_AO2p,R_PCTLOWWAGE,TotEmp,NatWalkInd
0,inside,2022-02-12 21:40:46,PMS5003+PMS5003+BME280,0,2.35,60375760012,576001,2,31080.0,"Los Angeles-Long Beach-Anaheim, CA",445.189692,166.96547,278.224222,257.310620,2779,1960.0,1667.0,0.787,0.079784,0.552490,0.367726,0.155947,36518,19.166667
1,inside,2022-02-12 21:40:24,PMS5003+PMS5003+BME280,1,2.25,60374309011,430901,1,31080.0,"Los Angeles-Long Beach-Anaheim, CA",111.226876,0.00000,111.226876,111.226876,1509,593.0,548.0,0.654,0.029197,0.459854,0.510949,0.235714,817,19.166667
2,outside,2022-02-12 21:41:08,PMS5003+PMS5003+BME280,0,9.61,60374309011,430901,1,31080.0,"Los Angeles-Long Beach-Anaheim, CA",111.226876,0.00000,111.226876,111.226876,1509,593.0,548.0,0.654,0.029197,0.459854,0.510949,0.235714,817,19.166667

In [114]:
# filtering out indoor AQ sensors...
la_cleaning5 = la_cleaning4[la_cleaning4['location_type']=='outside']

# checking if any sensors have been offline for a while...
la_cleaning5['last_seen'].sort_values().head(10)

516    2018-05-07 22:31:01
579    2019-03-06 21:39:07
78     2022-01-16 17:55:01
222    2022-01-16 22:35:20
10     2022-01-18 01:39:32
112    2022-01-18 15:42:33
168    2022-01-21 07:24:07
134    2022-01-22 22:04:40
225    2022-01-23 03:44:37
474    2022-01-26 08:27:06
Name: last_seen, dtype: object

In [115]:
# let's drop the first 2 since the sensors haven't been online in the last month
la_cleaning6 = la_cleaning5.drop([516, 579])       #['last_seen'].sort_values().head(10)

In [116]:
la_cleaning6.drop(columns=['location_type'], inplace=True)

In [117]:
la_cleaning6.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 472 entries, 2 to 611
Data columns (total 23 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   last_seen     472 non-null    object
 1   model         472 non-null    object
 2   age           472 non-null    int64
 3   1week_avg     472 non-null    float64
 4   fips_id       472 non-null    int64
 5   TRACTCE       472 non-null    int64
 6   BLKGRPCE      472 non-null    int64
 7   CBSA          472 non-null    float64
 8   CBSA_Name     472 non-null    object
 9   Ac_Total      472 non-null    float64
 10  Ac_Water      472 non-null    float64
 11  Ac_Land       472 non-null    float64
 12  Ac_Unpr       472 non-null    float64
 13  TotPop        472 non-null    int64
 14  CountHU       472 non-null    float64
 15  HH            472 non-null    float64
 16  P_WrkAge      472 non-null    float64
 17  Pct_AO0       472 non-null    float64
 18  Pct_AO1       472 non-null    float64
 19  Pct_AO2p      472 non-null    float64
 20  R_PCTLOWWAGE  472 non-null    float64
 21  TotEmp        472 non-null    int64
 22  NatWalkInd    472 non-null    float64
dtypes: float64(14), int64(6), object(3)
memory usage: 88.5+ KB

In [118]:
# YAY, no nulls!

la_cleaning6.isna().sum()

last_seen       0
model           0
age             0
1week_avg       0
fips_id         0
TRACTCE         0
BLKGRPCE        0
CBSA            0
CBSA_Name       0
Ac_Total        0
Ac_Water        0
Ac_Land         0
Ac_Unpr         0
TotPop          0
CountHU         0
HH              0
P_WrkAge        0
Pct_AO0         0
Pct_AO1         0
Pct_AO2p        0
R_PCTLOWWAGE    0
TotEmp          0
NatWalkInd      0
dtype: int64

In [125]:
la_clean = la_cleaning6.groupby('fips_id').mean()
la_clean.head(3)

,age,1week_avg,TRACTCE,BLKGRPCE,CBSA,Ac_Total,Ac_Water,Ac_Land,Ac_Unpr,TotPop,CountHU,HH,P_WrkAge,Pct_AO0,Pct_AO1,Pct_AO2p,R_PCTLOWWAGE,TotEmp,NatWalkInd
fips_id,,,,,,,,,,,,,,,,,,,
60371013001,1.0,12.45,101300.0,1.0,31080.0,341.127480,0.000000,341.127480,314.83253,1338.0,453.0,428.0,0.618,0.035047,0.116822,0.848131,0.254167,227.0,12.666667
60371021071,0.0,5.09,102107.0,1.0,31080.0,2054.619450,3.398366,2051.221084,1245.92677,2731.0,876.0,849.0,0.646,0.015312,0.199058,0.785630,0.264922,284.0,5.666667
60371031011,1.0,7.00,103101.0,1.0,31080.0,434.811739,0.000000,434.811739,276.88087,1420.0,617.0,557.0,0.652,0.017953,0.140036,0.842011,0.249023,158.0,7.333333

In [126]:
# Correlation of AQ with other features

AQ_corrs = pd.DataFrame(la_clean.corr()['1week_avg']).sort_values(by='1week_avg')
AQ_corrs

              1week_avg
Pct_AO2p      -0.259135
Ac_Land       -0.229425
Ac_Total      -0.225996
Ac_Unpr       -0.189990
TotPop        -0.152319
CountHU       -0.124691
HH            -0.122820
R_PCTLOWWAGE  -0.109393
TRACTCE        0.014844
Ac_Water       0.061188
BLKGRPCE       0.069368
TotEmp         0.079167
age            0.103156
P_WrkAge       0.131407
Pct_AO1        0.223011
Pct_AO0        0.226986
NatWalkInd     0.381670
1week_avg      1.000000
CBSA                NaN

In [85]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

X = la_clean[['TotPop', 'Ac_Water', 'Ac_Land', 'Ac_Unpr', 'Pct_AO0', 'Pct_AO1', 'Pct_AO2p', 'NatWalkInd']]
y = la_clean['1week_avg']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

ss=StandardScaler()
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

dummy = DummyRegressor(strategy="mean")
dummy.fit(X_train_scaled, y_train)
preds_dum = dummy.predict(X_test_scaled)
print('Dummy training score: ', dummy.score(X_train_scaled, y_train).round(4))
print('Dummy testing score: ', dummy.score(X_test_scaled, y_test).round(4))
print('MSE: ', mean_squared_error(y_test, preds_dum, squared=False).round(4))

Dummy training score:  0.0
Dummy testing score:  -0.0017
MSE:  5.6247

In [69]:
lr = LinearRegression(n_jobs=-1)
lr.fit(X_train_scaled, y_train)
preds_lr = lr.predict(X_test_scaled)

print('LR training score: ', lr.score(X_train_scaled, y_train).round(4))
print('LR testing score: ', lr.score(X_test_scaled, y_test).round(4))
print('MSE: ', mean_squared_error(y_test, preds_lr, squared=False).round(4))

LR training score:  0.2072
LR testing score:  0.1257
MSE:  5.2548

In [84]:
pd.DataFrame(zip(X_test.columns, lr.coef_)).sort_values(by=1)

            0         1
2     Ac_Land -0.713477
0      TotPop -0.119384
3     Ac_Unpr  0.063204
6    Pct_AO2p  0.327391
1    Ac_Water  0.444749
5     Pct_AO1  0.637075
4     Pct_AO0  0.752486
7  NatWalkInd  1.352700

In [74]:
lr.intercept_

9.905134038800705